### ISSUE TITLE
Can't reactivate twofactor_gateway

### ISSUE THREAD

**Issue by binford6000** [nextcloud/twofactor_gateway#226]
I deactivated twofactor_gateway some days ago and wanted to reactivate it. When i enter my identification it says: "Could not verify your code. Please try again". This could be found in the log:

`[index] Error: UnexpectedValueException: Only integers, floats and strings are allowed as value at <<closure>>

 0. /var/www/cloud/apps/twofactor_gateway/lib/Service/Gateway/Telegram/Gateway.php line 107
    setUserValue("admin", "twofactor_gateway", "telegram_chat_id", null)
 1. /var/www/cloud/apps/twofactor_gateway/lib/Service/Gateway/Telegram/Gateway.php line 75
    getChatId(OC\User\User {}, Telegram\Bot\Api {}, 123456789)
 2. /var/www/cloud/apps/twofactor_gateway/lib/Service/SetupService.php line 92
    send(OC\User\User {}, "123456789", "253871 is your  ... .")
 3. /var/www/cloud/apps/twofactor_gateway/lib/Controller/SettingsController.php line 90
    startSetup(OC\User\User {}, "telegram", "123456789")
 4. /var/www/cloud/lib/private/AppFramework/Http/Dispatcher.php line 166
    startVerification("telegram", "123456789")
 5. /var/www/cloud/lib/private/AppFramework/Http/Dispatcher.php line 99
    executeController(OCA\TwoFactorGat ... {}, "startVerification")
 6. /var/www/cloud/lib/private/AppFramework/App.php line 118
    dispatch(OCA\TwoFactorGat ... {}, "startVerification")
 7. /var/www/cloud/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
    main("OCA\\TwoFactorG ... r", "startVerification", OC\AppFramework\ ... {}, {gateway: "teleg ... "})
 8. <<closure>>
    __invoke({gateway: "teleg ... "})
 9. /var/www/cloud/lib/private/Route/Router.php line 297
    call_user_func(OC\AppFramework\ ... {}, {gateway: "teleg ... "})
10. /var/www/cloud/lib/base.php line 987
    match("/apps/twofactor ... t")
11. /var/www/cloud/index.php line 42
    handleRequest()

POST /apps/twofactor_gateway/settings/telegram/verification/start
from 91.67.178.10 by admin at 2019-04-17T19:28:16+00:00`

What can i do to reactivate twofactor_gateway?
Kind regards,
Sebastian

**Comment by ChristophWurst** [comment]
Apparently an invalid value type is passed as parameter. I assume it is `null`.

In the case of Telegram this is a bit of a problem because the `/start` message is only sent once.

**Comment by ChristophWurst** [comment]
This won't help solving your issue but it's a known bug/limitation: https://github.com/nextcloud/twofactor_gateway/blob/95f36e7bbfaf2d04ffd3c3c3fa2b22352e20bf18/lib/Service/Gateway/Telegram/Gateway.php#L104

**Comment by ChristophWurst** [comment]
This is likely related to https://github.com/nextcloud/twofactor_gateway/issues/110. Unfortunately I have not found the time yet to work on that as this app is low on my priority list, so any help would be highly appreciated :raised_hands:

**Comment by parreitu** [comment]
Hi
I've made a test. I've edited the **getChatId** function of this file

[https://github.com/nextcloud/twofactor_gateway/blob/95f36e7bbfaf2d04ffd3c3c3fa2b22352e20bf18/lib/Service/Gateway/Telegram/Gateway.php#L86](https://github.com/nextcloud/twofactor_gateway/blob/95f36e7bbfaf2d04ffd3c3c3fa2b22352e20bf18/lib/Service/Gateway/Telegram/Gateway.php#L86)

Replacing

**$chatId = $this->config->getUserValue($user->getUID(), 'twofactor_gateway', 'telegram_chat_id', null);**

by this line (suppose that 999999 is my chat_id)

**$chatId = 999999**

With this change, all is ok. I can configure the gateway, I get the verification code on my telegram APP , I can deactivate and activate again the twofactor_gateway, ..., all is OK.

All the problems related by @Dretech in this issue  #110 appear to be solved.

So, in consequence, I think that the problem is in this line, it isn't getting the number (our chat_id) that we previously have introduced in the **verify box**

**$chatId = $this->config->getUserValue($user->getUID(), 'twofactor_gateway', 'telegram_chat_id', null);**

I don't know how to make this changes in PHP, but it could be a good clue to solve the issue.

**Comment by binford6000** [comment]
Hi parreitu,
that works for me, too! Made my day ;-) 
Sebastian

**Comment by Dretech** [comment]
Hello Parreitu,

You found the cause why the Telegram 2fa app is not working in Nextcloud. When I change the chatid by the way you described, the app is working! Thanks.

@ChristophWurst can you change line 86 of /lib/Service/Gateway/Telegram/Gateway.php in a way that this line uses the user id entered in the web interface?

Dretech

**Comment by ChristophWurst** [comment]
It's on my todo!
